# Generated by Django 5.0.7 on 2024-07-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_alter_recipe_id_alter_recipe_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
