# Generated by Django 4.2.6 on 2024-07-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_recipe_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
